
namespace: antomain

external:
  externalImageUrl: "http://localhost:31380/api/images/"

frontendService:
  serviceAccount:
      name: frontend-service-account
  image:
      tag: main
      imagePullPolicy: Always
  service:
      type: ClusterIP

imageService:
  serviceAccount:
      name: image-service-account
  image:
    tag: main
    imagePullPolicy: Always
  service:
    type: ClusterIP

messageService:
  serviceAccount:
      name: message-service-account
  image:
      tag: main
      imagePullPolicy: Always
  service:
      type: ClusterIP

userService:
  serviceAccount:
      name: user-service-account
  image:
      tag: main
      imagePullPolicy: Always
  service:
      type: ClusterIP
  secret:
      jwtsecret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecret
      jwttokenlifetimeminutes: 60

postgreSql:
  serviceAccount:
      name: postgresql-service-account
  image:
      tag: latest
      imagePullPolicy: IfNotPresent
  service:
      type: ClusterIP
  secret:
      dbname: antomain
      username: dbantomain
      password: dbantomain