apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: Antomain
    service: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Antomain
      service: frontend-service
  template:
    metadata:
      labels:
        app: Antomain
        service: frontend-service
    spec:
      serviceAccountName: {{ .Values.frontendService.serviceAccount.name }}
      containers:
        - name: frontend-service
          image: "leowenex/antomain-cloudnative-frontend:{{ .Values.frontendService.image.tag }}"
          imagePullPolicy: {{ .Values.frontendService.image.imagePullPolicy }}
          ports:
            - containerPort: 3000