apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: Antomain
    service: frontend-service
spec:
  type: {{ .Values.frontendservice.service.type }}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: Antomain
    service: frontend-service