apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
      app: Antomain
      service: postgres-service
stringData:
  POSTGRES_DB: 'antomain'
  POSTGRES_PASSWORD: 'dbantomain'
  POSTGRES_USER: 'dbantomain'