apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: {{ .Values.namespace }}
  labels:
    app: Antomain
    service: postgres-service
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: Antomain
    service: postgres-service