apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
      app: Antomain
      service: postgres-service
stringData:
  POSTGRES_DB: "{{ .Values.postgresql.secret.dbname }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.secret.password }}"
  POSTGRES_USER: "{{ .Values.postgresql.secret.username }}"