apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: Antomain
    service: postgres-service
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: Antomain
    service: postgres-service