apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: Antomain
    service: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Antomain
      service: user-service
  template:
    metadata:
      labels:
        app: Antomain
        service: user-service
    spec:
      containers:
        - name: user-service
          image: "leowenex/antomain-cloudnative-userservice:{{ .Values.userservice.image.tag }}"
          imagePullPolicy: {{ .Values.userservice.image.imagePullPolicy }}
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: user-secret
          volumeMounts:
            - name: images-volume
              mountPath: /images
      volumes:
        - name: images-volume
          persistentVolumeClaim:
            claimName: user-service-pvc
      imagePullSecrets:
        - name: regcred