apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: Antomain
    service: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Antomain
      service: user-service
  template:
    metadata:
      labels:
        app: Antomain
        service: user-service
    spec:
      containers:
        - name: user-service
          image: leowenex/antomain-cloudnative-userservice:pr-4
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - secretRef:
                name: user-secret