apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  labels:
    app: Antomain
    service: user-service
stringData:
  POSTGRES_URL: 'postgres-service'
  POSTGRES_PORT: '5432'
  POSTGRES_DB: 'antomain'
  POSTGRES_PASSWORD: 'dbantomain'
  POSTGRES_USER: 'dbantomain'
  JWT_SECRET: 'secretsecretsecretsecretsecretsecretsecretsecretsecretsecret'
  JWT_TOKEN_LIFETIME_MINUTES: '60'
  MESSAGE_SERVICE_URL: 'http://message-service'
