apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: Antomain
    service: user-service
stringData:
  POSTGRES_URL: 'postgres-service'
  POSTGRES_PORT: '5432'
  POSTGRES_DB: "{{ .Values.postgresql.secret.dbname }}"
  POSTGRES_PASSWORD: "{{ .Values.postgresql.secret.password }}"
  POSTGRES_USER: "{{ .Values.postgresql.secret.username }}"
  JWT_SECRET: "{{ .Values.userservice.secret.jwtsecret }}"
  JWT_TOKEN_LIFETIME_MINUTES: "{{ .Values.userservice.secret.jwttokenlifetimeminutes }}"
  MESSAGE_SERVICE_URL: 'http://message-service'
  IMAGES_SERVICE_URL: 'http://image-service'
  USER_SERVICE_IMAGES_URL: "{{ .Values.external.externalImageUrl }}"
