apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-service-pv
  labels:
    app: Antomain
    service: user-service
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/images"