apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-pvc
  labels:
    app: Antomain
    service: user-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi