apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: image-circuitbreaker
  namespace: {{ .Values.namespace }}
spec:
  host: image-service.{{ .Values.namespace }}.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 10s
        tcpKeepalive:
          time: 7200s
          interval: 75s

# See https://istio.io/latest/docs/reference/config/networking/destination-rule/
