apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deployment
  labels:
    app: Antomain
    service: image-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Antomain
      service: image-service
  template:
    metadata:
      labels:
        app: Antomain
        service: image-service
    spec:
      containers:
        - name: image-service
          image: "leowenex/antomain-cloudnative-imageservice:{{ .Values.imageservice.image.tag }}"
          imagePullPolicy: {{ .Values.imageservice.image.imagePullPolicy }}
          ports:
            - containerPort: 8083
          volumeMounts:
            - name: images-volume
              mountPath: /images
      volumes:
        - name: images-volume
          persistentVolumeClaim:
            claimName: image-service-pvc
      imagePullSecrets:
        - name: regcred