apiVersion: v1
kind: Service
metadata:
  name: image-service
  namespace: {{ .Values.namespace }}
  labels:
    app: Antomain
    service: image-service
spec:
  type: {{ .Values.imageService.service.type }}
  ports:
    - port: 80
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app: Antomain
    service: image-service