apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-service-pv
  labels:
    app: Antomain
    service: image-service
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/image-service-data/images"