apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-service-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: Antomain
    service: image-service
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi