apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: Antomain
    service: message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Antomain
      service: message-service
  template:
    metadata:
      labels:
        app: Antomain
        service: message-service
    spec:
      containers:
        - name: message-service
          image: "leowenex/antomain-cloudnative-messageservice:{{ .Values.messageservice.image.tag }}"
          imagePullPolicy: {{ .Values.messageservice.image.imagePullPolicy }}
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: message-secret