apiVersion: v1
kind: Service
metadata:
  name: message-service
  labels:
    app: Antomain
    service: message-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: Antomain
    service: message-service