apiVersion: v1
kind: Secret
metadata:
  name: message-secret
  labels:
    app: Antomain
    service: message-service
stringData:
  POSTGRES_URL: 'postgres-service'
  POSTGRES_PORT: '5432'
  POSTGRES_DB: 'antomain'
  POSTGRES_PASSWORD: 'dbantomain'
  POSTGRES_USER: 'dbantomain'