apiVersion: v1
kind: Secret
metadata:
  name: message-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: Antomain
    service: message-service
stringData:
  POSTGRES_URL: 'postgres-service'
  POSTGRES_PORT: '5432'
  POSTGRES_DB: "{{ .Values.postgreSql.secret.dbname }}"
  POSTGRES_PASSWORD: "{{ .Values.postgreSql.secret.password }}"
  POSTGRES_USER: "{{ .Values.postgreSql.secret.username }}"