apiVersion: v1
kind: Service
metadata:
  name: message-service
  namespace: {{ .Values.namespace }}
  labels:
    app: Antomain
    service: message-service
spec:
  type: {{ .Values.messageService.service.type }}
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: Antomain
    service: message-service